version: "3.9"
services:
  product-container:
    build: ./product/
    volumes:
      - ./:/app-product
  account-container:
    build: ./account/
    volumes:
      - ./:/app-account
  mongo-database:
    container_name: 'mongo-ecomm'
    image: mongo:5
    ports:
      - 3002:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret